## Lecture 2 - Numpy - 1D-2D

In [18]:
# Câu 1: Tạo và thao tác ở mảng 2D
# a) Tạo một ma trận 2 chiều có kích thước 4x4 với các giá trị ngẫu nhiên từ 1 đến 16.
import numpy as np
arr_2d = np.random.randint(1, 17, size=(4, 4))

print(arr_2d)

[[ 9  2  3 10]
 [ 5 12 15 14]
 [15 15  8 12]
 [13  7  5  5]]


In [19]:
# b) Dựa vào ma trận 2D ở câu 1, truy cập và in ra (i) dữ liệu của hàng thứ 2, và (ii) cột thứ 3
hang_2 = arr_2d[1]
print(hang_2)
cot_3 = arr_2d[:, 2]
print(cot_3)

[ 5 12 15 14]
[ 3 15  8  5]


In [20]:
# c) Dựa vào ma trận 2D ở câu 1, tạo ra mảng con với tên sub_arr bằng cách lấy từ cắt mảng từ hàng 1 đến 3 và cột 2 đến 4
sub_arr = arr_2d[1:4, 2:5]
print(sub_arr)

[[15 14]
 [ 8 12]
 [ 5  5]]


In [21]:
# d) Dựa vào ma trận 2D ở câu 1, thay đổi giá trị của cột thứ 0 thành giá trị 10
arr_2d[:, 0] = 10
print("Ma trận 2D sau khi thay đổi:")
print(arr_2d)

Ma trận 2D sau khi thay đổi:
[[10  2  3 10]
 [10 12 15 14]
 [10 15  8 12]
 [10  7  5  5]]


In [22]:
# e) Dựa vào ma trận 2D ở câu 1, Tính tổng của mỗi hàng
tong_hang = arr_2d.sum(axis=1)
print("Tổng của mỗi hàng:")
print(tong_hang)

Tổng của mỗi hàng:
[25 51 45 27]


In [23]:
# f) Dựa vào ma trận 2D ở câu 1, truy cập và in ra các phần tử lớn hơn giá trị trung bình
gia_tri_trung_binh = np.mean(arr_2d)
print("Giá trị trung bình:", gia_tri_trung_binh)

cac_phan_tu_lon_hon_trung_binh = arr_2d[arr_2d > gia_tri_trung_binh]
print("Các phần tử lớn hơn giá trị trung bình:")
print(cac_phan_tu_lon_hon_trung_binh)


Giá trị trung bình: 9.25
Các phần tử lớn hơn giá trị trung bình:
[10 10 10 12 15 14 10 15 12 10]


##### **QUESTION 2**
Dựa vào `np.arange` và `np.reshape` để tạo ra ma trận 3x3 với kết quả cụ thể như sau:
$$
\begin{bmatrix}
    10 & 11 & 12\\
    13 & 14 & 15\\
    16 & 17 & 18
\end{bmatrix}\\
$$
Dựa vào ma trận vừa tạo, Hãy tính tổng theo từng dòng

In [24]:
# Trả lời câu 2:
arr = np.arange(10, 19)
matran_3x3 = np.reshape(arr, (3, 3))
print(matran_3x3)

tong_dong = matran_3x3.sum(axis=1)
print('tổng dòng',tong_dong)


[[10 11 12]
 [13 14 15]
 [16 17 18]]
tổng dòng [33 42 51]


In [25]:
# Câu 3: Xử lý dữ liệu trên mảng hai chiều
# a) Tạo một ma trận 5x5 với các giá trị ngẫu nhiên từ 0 đến 10.
matran_5x5 = np.random.randint(0, 11, size=(5, 5))
print(matran_5x5)

# b) Sử dụng np.where để tạo một ma trận mới, trong đó các giá trị lớn hơn 5 được thay thế bằng 1, và các giá trị không lớn hơn 5 được thay thế bằng 0.
matran_moi = np.where(matran_5x5 > 5, 1, 0)
print(matran_moi)

[[ 0  5  1 10  1]
 [ 9  9  6  5  5]
 [ 2  7  2  3  5]
 [ 3  3  4  9  0]
 [ 5  7  0  3  9]]
[[0 0 0 1 0]
 [1 1 1 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 1]]


#### c) Thay thế giá trị -1 vào các vị trí của ma trận ở câu b với kết quả dưới đây:
$$
\begin{bmatrix}
    0 & 1 & 0 & 0 & 1\\
   -1 & -1& -1 & -1 & -1\\
    0 & 1 & 0 & 0 & 1\\
    -1 & -1& -1 & -1 & -1\\
    0 & 1 & 0 & 0 & 1\\
\end{bmatrix}\\
$$

In [26]:
# Trả lời câu c
matran_moi[matran_5x5 <= 5] = -1
print(matran_moi)

[[-1 -1 -1  1 -1]
 [ 1  1  1 -1 -1]
 [-1  1 -1 -1 -1]
 [-1 -1 -1  1 -1]
 [-1  1 -1 -1  1]]


In [27]:
# d) Thay thế tất cả các số âm bằng giá trị tuyệt đối của chúng.
matran_moi = np.abs(matran_5x5)
print(matran_moi)
# e) Tính tổng của các phần tử trên mỗi hàng của ma trận mới.
tong_hang = matran_moi.sum(axis=1)
print(tong_hang)

[[ 0  5  1 10  1]
 [ 9  9  6  5  5]
 [ 2  7  2  3  5]
 [ 3  3  4  9  0]
 [ 5  7  0  3  9]]
[17 34 19 19 24]


#### Lecture 2: Numpy - Loại dữ liệu tự định nghĩa

Tạo một đối tượng có tên là sản phẩm với các thuộc tính như sau: mã sản phẩm (masp), tên sản phẩm (tensp), và giá sản phẩm (price), số lượng (soluong). Dữ liệu cụ thể như sau:


(1, 'Máy tính', 1200.50,10),
(2, 'Điện thoại Iphone 11', 699.99,20),
(3, 'USB', 89.95,20),
(4, 'Loa ', 499.50,30),
(5, 'Màn hình', 799.00,50)


Yêu cầu:

a) Tìm sản phẩm có giá cao nhất

b) Tính giá trung bình của tất cả sản phẩm

c) Tính doanh số bán, biết rằng doanh số bán bằng số lượng x đơn giá

d) Hiện thị thông tin sản phẩm gồm có tên sản phẩm và giá sản phẩm

In [28]:
data = np.array([
    (1, 'Máy tính', 1200.50, 10),
    (2, 'Điện thoại Iphone 11', 699.99, 20),
    (3, 'USB', 89.95, 20),
    (4, 'Loa', 499.50, 30),
    (5, 'Màn hình', 799.00, 50)
], dtype=[('masp', int), ('tensp', 'U30'), ('price', float), ('soluong', int)])

# a) Tìm sản phẩm có giá cao nhất
index_max_price = np.argmax(data['price'])
product_max_price = data[index_max_price]

print('Sản phẩm có giá cao nhất:')
print('Mã sản phẩm:', product_max_price['masp'])
print('Tên sản phẩm:', product_max_price['tensp'])
print('Giá sản phẩm:', product_max_price['price'])
print('Số lượng sản phẩm:', product_max_price['soluong'])


Sản phẩm có giá cao nhất:
Mã sản phẩm: 1
Tên sản phẩm: Máy tính
Giá sản phẩm: 1200.5
Số lượng sản phẩm: 10


In [29]:
# b) Tính giá trung bình của tất cả sản phẩm
average_price = np.mean(data['price'])

print('Giá trung bình của tất cả sản phẩm:', average_price)

Giá trung bình của tất cả sản phẩm: 657.788


In [30]:
#c) Tính doanh số bán, biết rằng doanh số bán bằng số lượng x đơn giá
doanh_so_ban = data['soluong'] * data['price']

In [31]:
# d) Hiện thị thông tin sản phẩm gồm có tên sản phẩm và giá sản phẩm
ten_sp = data['tensp']
gia_sp = data['price']

for i in range(len(data)):
    print('Sản phẩm:', ten_sp[i])
    print('Giá sản phẩm:', gia_sp[i])
    print('----------------------')

Sản phẩm: Máy tính
Giá sản phẩm: 1200.5
----------------------
Sản phẩm: Điện thoại Iphone 11
Giá sản phẩm: 699.99
----------------------
Sản phẩm: USB
Giá sản phẩm: 89.95
----------------------
Sản phẩm: Loa
Giá sản phẩm: 499.5
----------------------
Sản phẩm: Màn hình
Giá sản phẩm: 799.0
----------------------
